---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ld-prod-app4
  namespace: prod-app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.18-perl
        ports:
        - containerPort: 80
